const resources = {
  icons: {
    down: require('./icons/down.png'),
    language: require('./icons/language.png'),
    notification: require('./icons/notification.png'),
    user: require('./icons/user-shield.png'),
    trophyGold: require('./icons/trophy-gold.png'),
    trophy: require('./icons/trophy.png'),
    time: require('./icons/time.png'),
    walking: require('./icons/walking.png'),
    social: require('./icons/following.png'),
    convert: require('./icons/change.png'),
    diactive: require('./icons/hanukkahglass.png'),
    logout: require('./icons/logout.png'),
    userLogo: require('./icons/user.png'),
    password: require('./icons/secure.png'),
    email: require('./icons/email.png'),
    hidePass: require('./icons/passwordHide.png'),
    edit: require('./icons/edit.png'),
    user2: require('./icons/user2.png'),
    email2: require('./icons/email2.png'),
    password2: require('./icons/pass.png'),
    back: require('./icons/back.png'),
    search: require('./icons/search.png'),
    swipeLeft: require('./icons/swipe-left.png'),
    donate: require('./icons/donate.png'),
    ask: require('./icons/ask.png'),
    up: require('./icons/up.png'),
    dwn: require('./icons/dwn.png'),
    gift: require('./icons/gift.png'),
    lightTheme: require('./icons/lighttheme.png'),
    darkTheme: require('./icons/darktheme.png'),
    foot: require('./icons/foot.png'),
    shopping: require('./icons/shopping.png'),
    remove: require('./icons/remove.png'),
    diactiv: require('./icons/diactiv.png'),
    green_add: require('./icons/plus.png'),
    cancel: require('./icons/cancel.png'),
    green_take: require('./icons/moins.png'),
  },
  huawei: require('./images/huawei.png'),
  frozen: require('./images/frozen.png'),
  qrcode: require('./images/qrscan.png'),
  home: {
    ring: require('./images/home/ring.png'),
  },
  login: {
    logo: require('./images/login/icon.png'),
  },
  mascot: {
    walk: require('./images/mascot/run.png'),
    happy: require('./images/mascot/pngwing.png'),
    bighappy: require('./images/mascot/big-happy.png'),
  },
  onboarding: {
    step1: require('./images/onboarding/view-possum-cartoon-character.png'),
    step2: require('./images/onboarding/view-possum-cartoon-character.png'),
    background: require('./images/onboarding/background.png'),
  },
  auth: {
    illustration: require('./images/auth/illustration.png'),
  },
  profile: {
    profile: require('./images/profile/profile.png'),
    user: require('./images/profile/avatar.jpg'),
  },
  awards: {
    starFill: require('./images/awards/star-fill.png'),
    starWhite: require('./images/awards/star-white.png'),
    starEmpty: require('./images/awards/star-empty.png'),
    car: require('./images/awards/car.png'),
    product: require('./images/awards/product.png'),
    minus: require('./images/awards/plus.png'),
    plus: require('./images/awards/plus.png'),
    award: require('./images/awards/award.png'),
  },
  models: {
    labels: require('./data/model.json'),
    series: require('./data/model.json'),
    model: require('./data/model.json'),
    scaling: require('./data/scaling.json'),
  },
};
export default resources;
